spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///E:/Poli2023-1/PDS/Repos/config-data
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000

